name: Test Automation Framework

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install
        playwright install-deps
    
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
    
    - name: Run tests with Allure (Headless mode)
      run: |
        pytest tests/ --alluredir=allure-results --test-browser=${{ matrix.browser }} --headless -v
    
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report
    
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{ matrix.browser }}
        path: allure-report/
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.browser }}
        path: |
          allure-results/
          screenshots/
          test.log
    
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report-${{ matrix.browser }}
        path: report.html

  parallel-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install
        playwright install-deps
    
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
    
    - name: Run tests in parallel (Headless mode)
      run: |
        pytest tests/ --alluredir=allure-results --headless -n auto -v
    
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report
    
    - name: Upload parallel test report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-parallel
        path: allure-report/

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run security scan
      run: |
        pip install bandit safety
        bandit -r . -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json 